<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" Version="1.7.35" />
    <PackageReference Include="Hangfire.PostgreSql" Version="1.11.6" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../HvShop.Infrastructure/HvShop.Infrastructure.csproj" />
  </ItemGroup>
</Project>
